apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
  - reviews
  http:
  - match:
    - headers:
        Cookie: 
          exact: reviews-version=v1
    route:
    - destination:
        host: reviews
        subset: v1
  - match:
    - headers:
        Cookie:
          exact: reviews-version=v2
    route:
    - destination:
        host: reviews
        subset: v2   
  - route:
    - destination:
        host: reviews
        subset: v1
      headers:
        response:
          add:
            Set-Cookie: reviews-version=v1; Max-Age=2592000
      weight: 50
    - destination:
        host: reviews
        subset: v2
      headers:
        response:
          add:
            Set-Cookie: reviews-version=v2; Max-Age=2592000
      weight: 50
